### ISSUE TITLE
JavaScript Coding Challenges: Assignment Exercises

### ISSUE THREAD

**Issue by Pankaj-Str** [Pankaj-Str/JavaScript-Tutorial#4]
### Question 1: Temperature Converter
Create a temperature conversion utility with the following requirements:
- Develop functions to convert between Celsius and Fahrenheit
- Create variables to store input temperatures
- Implement rounding to one decimal place
- Generate descriptive output messages for each conversion
- Bonus: Add input validation to ensure only numeric values are processed

![image](https://github.com/user-attachments/assets/9d8d7bf1-f521-4937-bbef-8700f25b4f06)

### Question 2: Shopping Cart Calculator
Build a basic shopping cart pricing system:
- Create an array of product objects (each with name, price, quantity)
- Implement a function to calculate total cart value
- Apply a discount logic based on total purchase amount
- Calculate tax and shipping costs
- Generate a detailed receipt with itemized breakdown

![image](https://github.com/user-attachments/assets/cf9940c9-09ba-493b-9079-0ca64631be16)

### Question 3: Personal Finance Tracker
Design a simple expense tracking program:
- Create arrays to store monthly income and expenses
- Develop functions to:
  * Calculate total monthly income
  * Calculate total monthly expenses
  * Determine monthly savings percentage
- Implement conditional logic to provide financial advice based on savings

![image](https://github.com/user-attachments/assets/2bb69887-771a-48f8-9dab-15bdfb3bcf92)

### Question 4: String Manipulation Challenge
Create a text analysis utility:
- Write a function that accepts a string input
- Count total characters, words, and vowels
- Convert the string to different cases (uppercase, lowercase, title case)
- Check for palindromes
- Generate a comprehensive text analysis report

![image](https://github.com/user-attachments/assets/ef1212f2-9994-4466-81cc-11376f9dd1de)

### Question 5: Array Transformation Project
Develop advanced array manipulation methods:
- Create an array of numbers
- Implement functions to:
  * Filter even and odd numbers
  * Map values to their squares
  * Reduce the array to find maximum and minimum values
  * Sort the array in ascending and descending order
- Generate summary statistics about the array

![image](https://github.com/user-attachments/assets/efcd6f7f-05df-40e0-b211-9087e32ff6f4)

### Bonus Challenge: User Authentication Simulator
Create a basic user authentication system:
- Design an object to store user credentials
- Implement login and registration functions
- Add password strength validation
- Create a security check that prevents repeat passwords
- Generate user-friendly error and success messages

**Comment by RiddhiiA** [comment]
https://github.com/developology/JAVASCRIPT.git
